### ISSUE TITLE
Add LinkedIn to social providers.

### ISSUE THREAD

**Issue by ziadomalik** [zernonia/nuxt-lego#52]
Hello, I want to incorporate nuxt-lego into my personal project, which utilizes LinkedIn as an authentication provider. 
I would like to integrate it into this library. I propose the usage of the [LinkedIn logo](https://api.iconify.design/devicon:linkedin.svg) found in the [Devicon](https://icones.js.org/collection/devicon) collection.

In my upcoming PR, I would like to add this to `/layer/components/Lego/Auth/SocialProvider.vue`:

```ts
const providerInfo = {
  // ... other providers
  linkedin: { title: 'LinkedIn', icon: 'devicon:linkedin' },
}
```

**Comment by ziadomalik** [comment]
In my PR, I also intend to mention the support for LinkedIn within the website, under the 'Available Providers' section.

**Comment by zernonia** [comment]
Nice suggestion and PR here @ziadomalik ! Thanks for contributing!
