### ISSUE TITLE
Maybe missing import useProjection

### ISSUE THREAD

**Issue by bazuka5801** [zernonia/nuxt-lego#65]
https://github.com/zernonia/nuxt-lego/blob/8f0f40725956c11b7ce256ad953f3ade9a4fb3c1/website/components/Blueprints/MagnifiedDock/AppIcon.vue#L21

**Comment by zernonia** [comment]
Hi @bazuka5801 . Nope. useProjection from Vueuse will be auto-imported, thus no explicit import needed 😁
Thanks for the ticket none the less! 

Cheers! 😁
