### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by GeorgeDaris** [zernonia/nuxt-lego#66]
I'm running into this error after starting the local development server:

`RollupError: Could not resolve "../node_modules/nuxt-og-image/dist/runtime/nitro/renderers/satori
" from " virtual:#nuxt-og-image/provider"`

**Comment by zernonia** [comment]
Hey @GeorgeDaris ! I've updated the deps and running locally should be fine now. Closing. Thanks 😁

**Comment by GeorgeDaris** [comment]
Glad to hear, @zernonia!
