### ISSUE TITLE
component(SocialShare): add reddit on social share component

### ISSUE THREAD

**Issue by megatheikal** [zernonia/nuxt-lego#8]

**Comment by zernonia** [comment]
Seems like an easy one.
Would you like to contribute? 😁


I found this [Stackoverflow](https://stackoverflow.com/questions/24823114/post-to-reddit-via-url) that would help a ton

**Comment by megatheikal** [comment]
yes, i would like to contribute for this component. please assign me on this issue

**Comment by zernonia** [comment]
Merged in https://github.com/zernonia/nuxt-lego/pull/11
